### ISSUE TITLE
mkdirp is required

### ISSUE THREAD

**Issue by sichvoge** [mulesoft-labs/raml-generator#1]
If you create a project and include `raml-generator/bin` into it - you'll run into a dependency problem. `mkdirp` is missing. Adding it to your `package.json` should solve the issue. I'll create a pull request for it.

The final solution should look like:

``` json
"dependencies": {
    ...,
    "mkdirp": "^0.5.0"
  }
```

**Comment by blakeembrey** [comment]
Fixed in `master`, release in `v0.0.2` :+1:
