### ISSUE TITLE
question about raml-object-interface

### ISSUE THREAD

**Issue by opyate** [mulesoft-labs/raml-generator#12]
The README mentions https://github.com/mulesoft-labs/js-raml-object-interface but I can't find any other reference to it in the raml-generator sources or dependencies. What am I missing?

**Comment by blakeembrey** [comment]
You're right. It's not used anymore. That was in the initial version as an attempt to standardize and reuse the documentation and interface I'd already written. With `0.1` we switched it back to using an object directly and the README needs updating to reflect that.

**Comment by blakeembrey** [comment]
Closing with `1.0` release, uses the JSON from the `raml-1-parser` now.
