### ISSUE TITLE
Update outdated raml-parser

### ISSUE THREAD

**Issue by jenschude** [mulesoft-labs/raml-generator#15]
Currently the raml-generator uses the version 0.1.x of the raml-1-parser

The most recent version is 1.1.4 which resolves a lot of issues especially with reference resolution inside json schemas.

I just had overwritten locally the used parser version using shrinkwrap.json and the generator is working with 1.1.4 as well as now correctly resolving json schema references without OOM exceptions.

**Comment by jenschude** [comment]
Hi there,

any news on this or the pull request by me?

Thanks in advance

**Comment by jenschude** [comment]
@blakeembrey Just another try to catch some attention

**Comment by blakeembrey** [comment]
Sorry, I haven't worked on this project for over six months and don't have permission to do updates.

**Comment by sichvoge** [comment]
I commented on the PR
