### ISSUE TITLE
Loading RAML spec fails

### ISSUE THREAD

**Issue by sichvoge** [mulesoft-labs/raml-generator#3]
Loading the RAML fails as `ramlParser.loadFile(argv[0])` takes the first argument `argv[0]` which usually is `node`. It has to be changed to `ramlParser.loadFile(argv[2])` inside the raml-generator.js file.

**Comment by sichvoge** [comment]
BTW - the `README` should be updated as it could be confusing that you get a function back by using `{{stringify @getBaseUri}}` instead of the actual value. I'll create a PR for the initial problem and this enhancement. Feel free to skip the enhancement ;)

**Comment by blakeembrey** [comment]
@sichvoge I've fixed them both locally and trying to push now. The stringify example should be wrapped in parens for the function to evaluate and the argv example should have been `opts._[0]`.
