### ISSUE TITLE
Global install?

### ISSUE THREAD

**Issue by solsend2l** [mulesoft-labs/raml-generator#7]
So, this is cool - but I was expecting a simple renderer that outputs the HTML/etc. Possibly a way to make this `npm install -g raml-generator`?

**Comment by blakeembrey** [comment]
This project supports the architecture for something like that, but doesn't actually generate anything specifically. You can use this project to create a `raml-html-generator`. Think of it as a little boilerplate/flamework. Maybe you're after something more like https://github.com/kevinrenskers/raml2html?

**Comment by sichvoge** [comment]
@solsend2l - this is still a closed issue, but what do you want to achieve? we might be able to help you.

**Comment by solsend2l** [comment]
Hi - I think I'll just use `raml2html` for now :) Gratzi!

**Comment by solsend2l** [comment]
BWT, anyone know of a Handlebars template that generates dynamic "Try it" ajax calls for the various route methods? For live testing of the API instead of, say, a [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en) tool.

**Comment by sichvoge** [comment]
Have you had the chance to look at Osprey or the API Console with integrated Mocking and "Try it" functionality?
